### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by arnoudkooi** [Kannix2005/ha_siedle_python#1]
Im interested in this, would be curious if there is a way to open the door via an API.
Do you already have a work-in-progress file you can commit?

**Comment by Kannix2005** [comment]
Hey,
I´m currently on it. It´s rather difficuilt, because Siedle uses a propriatary OAuth protocol (figured that out) and the API calls are somewhat random. So i have to invest some more time into that.
Though i don´t know if it´s possible to trigger the door latch or anything else - need to investigate that.

**Comment by arnoudkooi** [comment]
Sounds challenging. Let me know if I can help.
 There probably isn't a port open on the IQ Unit itself you can send a command to?
